import type { Category, Difficulty } from "./categoryType";
import type { SoundSettings } from "./soundType";
import type { GameSettings, Team } from "./defaultValueType";
export type Id = string;

export type GameStore = {
  teams: Team[];
  gameSettings: GameSettings;
  addTeam: (team: Omit<Team, "id">) => void;
  removeTeam: (id: Id) => void;
  setGameSettings: (settings: GameSettings) => void;
  updateTeamName: (id: Id, name: string) => void;
  updateTeamPlayerCount: (id: Id, playerCount: number) => void;
  updatePlayerName: (teamId: Id, playerId: Id, name: string) => void;
  currentRound: number;
  currentTeamIndex: number;
  nextTurn: () => void;
  categories: Category[];
  usedWords: string[];
  pickWord: (categoryId: Id, difficulty: Difficulty) => string | null;
  currentWord: string | null;
  lastTurnWord: string | null;
  lastTurnCategoryId: Id | null;
  setCurrentWord: (word: string | null) => void;
  currentCategoryId: Id | null;
  currentDifficulty: Difficulty | null;
  rerollsUsed: number;
  selectWord: (categoryId: Id, difficulty: Difficulty) => void;
  rerollWord: () => void;
  correctGuess: () => void;
  skipGuess: () => void;
  lastTurnPoints: number | null;
  lastTurnTeamId: Id | null;
  soundSettings: SoundSettings;
  setSoundSettings: (settings: SoundSettings) => void;
  resetGame: () => void;
  resetAll: () => void;
  usedCategoryDifficulties: string[];
  gameTitle: string;
  setGameTitle: (title: string) => void;
};
